# Generated by Django 6.0.6 on 2026-07-05 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0002_auditoria_chat_privado_mensaje_privado_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion_tributaria',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='calificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Intranet.calificacion_tributaria'),
        ),
    ]
