# Generated by Django 5.1 on 2026-07-13 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0002_auditoria_chat_privado_mensaje_privado_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion_tributaria',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_tributarias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factor_calificacion',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='calificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='Intranet.calificacion_tributaria'),
        ),
    ]
